# Default values for qplay server.
app:
  name: qplay
  group: qplay
  replicaCount: 1
  container:
    image:
      repository: REPONAME/
      name: qplay
      tag: v0.0.1
    imageConfig:
      pullPolicy: IfNotPresent
    port: 3001
    config:
      - name: app-config
  service:
    type: ClusterIP
    port: 3001
    protocol: TCP
