apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
spec:
  ports:
  - port: {{ .Values.app.service.port }}
    protocol: {{ .Values.app.service.protocol }}
    targetPort: {{ .Values.app.container.port }}
  selector:
    app: {{ .Values.app.name }}
  type: {{ .Values.app.service.type }}
